### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by tianshaokai** [cangwang/MagicCamera3#1]
![image](https://user-images.githubusercontent.com/6706496/54349524-6674bf80-4686-11e9-899a-855d98d7d6ed.png)

**Comment by cangwang** [comment]
please set your gradle version ,my test project use these version in build.gradle

classpath 'com.android.tools.build:gradle:3.0.1'
classpath "com.android.tools.build:gradle-experimental:0.11.1"
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.0"

Can you tell me your versions or
you can change your versions and tell me if it can resolve this problem.Thank you!

**Comment by cangwang** [comment]
please check your Cmake has downloaded already,it will use cmake file to compile this project

**Comment by tianshaokai** [comment]
classpath 'com.android.tools.build:gradle:3.0.1'
classpath "com.android.tools.build:gradle-experimental:0.11.1"
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.0"

androidstudio version 3.3.2

**Comment by cangwang** [comment]
please check your Cmake has downloaded already,it will use cmake file to compile this project

**Comment by tianshaokai** [comment]
Yes ,Cmake has been downloaded. I found that the problem of changing the gradle and koltin versions was gone, but some new problems arose. I hope you can add some friends to solve these problems.

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/61115537-42ef4380-a4c5-11e9-97b3-1288a551cbb2.png)
找不到类
